accelerate launch \
    --config_file accelerate.yaml \
    --num_processes 8 \
    --gradient_accumulation_steps 4 \
    --main_process_port 19347 \
    ttrl_train.py \
    --learning_rate 5e-6 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --model_name_or_path Qwen/Qwen3-1.7B \
    --dataset_name MathArena/aime_2026 \
    --val_files MathArena/aime_2026 \
    --output_dir ./outputs/ttrl/ \
    --run_config qwen31b_ttrl \
    --num_train_epochs 2000 \
    --num_iterations 2 \
    --gradient_checkpointing \
    --lora_r 64 \
    --lora_alpha 128 \
    --lora_target_modules q_proj k_proj v_proj o_proj gate_proj up_proj down_proj \
    --max_prompt_length 2048 \
    --max_completion_length 16000 \
    --num_generations 8 \
    --temperature 1.2 \
    --use_vllm \
    --use_peft \
    --vllm_mode colocate \
    --logging_steps 2 \
    --save_steps 20 \
    --beta 0.0 \
    --loss_type grpo \
    --scale_rewards group \
    --min_consensus_count 2 \
    --vllm_enable_sleep_mode True \
    --test_freq -1 \
    --wandb_project TTRL
