accelerate launch \
    --config_file accelerate.yaml \
    --num_processes 4 \
    --gradient_accumulation_steps 8 \
    --main_process_port 0 \
    ttpo_train.py \
    --model_name_or_path Qwen/Qwen3-4B \
    --dataset_name siyanzhao/Openthoughts_math_30k_opsd \
    --learning_rate 5e-6 \
    --max_grad_norm 0.1 \
    --per_device_train_batch_size 1 \
    --gradient_checkpointing \
    --gradient_accumulation_steps 8 \
    --output_dir ./outputs/ttpo \
    --run_config qwen34b_ttpo_openthoughts \
    --max_steps 27600 \
    --max_tokens 1024 \
    --max_completion_length 16000 \
    --save_steps 25 \
    --logging_steps 1 \
    --attn_implementation flash_attention_2 \
    --torch_dtype bfloat16 \
    --max_length 20000 \
    --kl_mode -3 \
    --use_vllm \
    --vllm_mode colocate \
    --vllm_gpu_memory_utilization 0.6 \
    --vllm_tensor_parallel_size 1 \
    --use_peft \
    --lora_r 64 \
    --lora_alpha 128 \
    --lora_target_modules q_proj k_proj v_proj o_proj gate_proj up_proj down_proj \
    --temperature 1.1 \
    --top_p 0.95 \
    --top_k 20 \
    --lmbda 1 \
    --num_rollouts 64 \
    --num_train_rollouts 8 \
    --jsd_clip_mode element \
    --positive_fraction 0.5 \
    --pos_select 0 \
    --neg_select 0 \
    --rl_weight 0.1 \
    --token_weighting_retention 0.0 \
    --use_token_masking True \
    --privilege_info answer \
    --jsd_token_clip 0.05 \
    --fixed_teacher \
    --wandb_project TTPO
